name: auth_usage_quota
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  either_dart: ^0.4.0
  firedart: ^0.9.2
  freezed_annotation: ^2.2.0
  grpc: ^3.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  very_good_analysis: ^4.0.0
